### ISSUE TITLE
Age as a range

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-schemablocks/blocks#8]
Please comment on the points raised here, and the accompanying PR #7.

(Text below copied from #7):

The representation of ages of unknown "point value", but lying within a certain range, is a requirement in the representation of many biomedical data collections. Typical instances here would be clinical studies with known inclusion ages ("adults 18-65ys") or research projects targeting age delimited populations, without individual age data.

It has not escaped our notice[<sup>TM</sup>](http://www.lablit.com/article/11) that the representation of an `age_range` in conformance with the [FHIR Range model](http://build.fhir.org/datatypes.html#Range) (sorted array of 1 or 2 values; thanks @julesjacobsen) would obviate the need of an atomic `age` attribute; but this is a topic for discussion.

Please note that the fix of the "age_class" example is separately covered in #6 .

For the code review, please focus on the [YAML source file](https://github.com/ga4gh-schemablocks/blocks/compare/Age-age-to-range?expand=1#diff-8af9914a343a0bb2fe756c7c70d45db0).

Code for `age` and `age_range` attributes of the `Age` class:

```
    properties:
      age:
        description: |
          The age as ISO8601 string.
        type: string
        example: 'P12Y'
      age_range:
        description: |
          The age as an array of 1 or 2 ordered ISO8601 strings. This can be 
          used either for a specific age or to express a known age range - e.g.
          the minimum and maximum age of patients included in a study.
          The format corresponds to the general "Range" type in FHIR.
        type: array
        format: string
        example:
          - 'P13Y'
          - 'P18Y'
```

**Comment by Relequestual** [comment]
I like the ISO 8601 way of referencing an age or range. Interesting.

I'm all for using existing standards, but should we consider the barrier to entry for accessing the ISO specification documents? I found some details via searching, but it looks like I have to pay to view the specification document. Is that correct?

(referencing https://github.com/phenopackets/phenopacket-schema/issues/30 as it is linked to this issue.)

**Comment by julesjacobsen** [comment]
Actually the FHIR range isn't a sorted array, its a datatype with two fields containing a ```Quantity```:

```json
{
  "low" : { Quantity(SimpleQuantity) },
  "high" : { Quantity(SimpleQuantity) }
}
```
Where ```Quantity``` is defined as: (sorry about the ```//```. Need to learn json-schema...)
```json
{
  "value" : "<decimal>", // Numerical value (with implicit precision)
  "comparator" : "<code>", // < | <= | >= | > - how to understand the value
  "unit" : "<string>", // Unit representation
  "system" : "<uri>", // System that defines coded unit form
  "code" : "<code>" // Coded form of the unit
}
```
 So I think it would look like this:

```json
{
  "low": {
    "value": 13.0,
    "comparator": ">=",
    "unit": "year",
    "system": "http://unitsofmeasure.org/",
    "code": "a"
  },
  "high": {
    "value": 18.0,
    "comparator": "<=",
    "unit": "year",
    "system": "http://unitsofmeasure.org/",
    "code": "a"
  }
}
```

@Relequestual 's point about accessibility is a good point. Not trying to sound like a FHIR fanatic, they have chosen to use [UCUM](http://unitsofmeasure.org/ucum.html), possibly for this reason. Another good reason is that there are libraries available for parsing these and they have a well specified syntax with formal BNF specification. This was something ISO 8601 didn't/doesn't have and one of the reasons the [IETF have a different standard](https://www.ietf.org/rfc/rfc3339.txt) which required something less complex.

**Comment by mbaudis** [comment]
@julesjacobsen Re.: not array: Correct, I was simplifying; but awkward with the "low or high may be missing"...

IETF is a profile on ISO8601, which, like the W3C implementation note, avoids the definition of non-timepoint variants (such as durations).

Since time points are always defined based on ISO, and durations such as age can be defined as ISO string, without a separate "unit" attribute, it seems sensible to use this in a standard schema definition, and awkward (though obviously doable) to specify a different standard.

I agree that it is not helpful to have the official documentation not available for free, but then, this is SOP for some of those organisations; and external documentations of the standards are commonplace (see e.g. W3C profile for time points; SAS documentation http://support.sas.com/documentation/cdl/en/lrdict/64316/HTML/default/viewer.htm#a003169814.htm). 

I have no problem to provide the new 2019 edition (haven't seen this myself).

**Comment by pnrobinson** [comment]
@mbaudis what do you think of 
```
message {
  Age start=1;
  Age end=2;
}

**Comment by mbaudis** [comment]
@pnrobinson That is certainly fine; so the `Age_class` would be defined as one of:

- an ontology
- a "numerical" (i.e. ISO or number & unit etc.) `age`
- an `age_range`, consisting of 2 `age` entries

---

I personally have the tendency to have all potentially fuzzy values expressed as arrays; this makes it so much easier to parse by using only one method (you always look for the upper and lower value, which may be the same). But I'm not dogmatic about this (neither am I successful in convincing ppl.)

**Comment by julesjacobsen** [comment]
@mbaudis the problem with having

```proto
message Age {
    string age = 1;
    OntologyClass age_class = 2;
    AgeRange = 3;
}

message AgeRange {
  Age start=1;
  Age end=2;
}
```

is that Age can then infinitely recurse through the AgeRange.

So really it needs modelling like this:

```proto

message Something {
    oneof age_of_something {
        Age age = 1;
        AgeRange age_range = 2;
    }
}

message Age {
    string age = 1;
    OntologyClass age_class = 2;
}

message AgeRange {
    Age start = 1;
    Age end = 2;
}
```

**Comment by mbaudis** [comment]
@julesjacobsen But in my note I specified `a "numerical" (i.e. ISO or number & unit etc.) age` - which could be declared as a separate `Age` class or just "format documented" in the different positions. Here w/o class for the "numerical" age.

In contrast to your example, I see the ontology class age as sufficient for both age & age range.

```
AgeClass:
  description: "one of the parameters"
  parameters:
    - age:
        type: string
        example: "P12Y3M"
    - age_range:
        value: $ref/AgeRange
        example:
          start: "P13Y"
          end: "P18Y"
    - age_class:
        value: $ref/OntologyTerm
        example:
          type: "__ageOntoLabel__"
          id: "__ageOntoTerm__"
AgeRange:
  parameters:
   - start:
        type: string
        example: "P13Y"
   - end:
        type: string
        example: "P18Y"
  ```

Too many ages, too little time.
